services:
  api:
    build: .
    ports:
      - "8567:7860"
    environment:
      # Local dev : SQLite (aucune dépendance externe)
      DATABASE_URL: sqlite:///./attrition.db
      ENVIRONMENT: dev
    volumes:
      - ./ml_models:/app/ml_models
      - ./data:/app/data
      - ./attrition.db:/app/attrition.db
