name: Deploy to Hugging Face Spaces

on:
  push:
    tags: ["v*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push vers Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://HF_USER:$HF_TOKEN@huggingface.co/spaces/${{ secrets.HF_SPACE_NAME }}
          git push hf HEAD:main --force
